### ISSUE TITLE
Launching product from the spoke account creates stack in the Hub Account.

### ISSUE THREAD

**Issue by Larry322** [aws-samples/aws-service-catalog-reference-architectures#50]
In continuation to issue 47: 

After adding principals I am able to see the product lists in spoke account. However when I launch the product from the spoke account (not the hub acccount), the stack is created in the Hub Account. 

Git --> Pipeline (Hub Account) --> Portfolio (Hub Account) -> Shared with Spoke Account

Spoke Account --> Launch Products --> Creating the product in Hub Accout

Ideally I would like to have this set up, just create the portfolio only in the Hub account and share it. Is this possible with this design..  If it is not possible I think I may have to create the portfolios in all the account by supplying all the Hub Account IDs during the stack set creation for this portfolio.

Am I missing something? Thanks for your help.

_Originally posted by @Larry322 in https://github.com/aws-samples/aws-service-catalog-reference-architectures/issues/47#issuecomment-544251657_

**Comment by chapmancl** [comment]
This is the designed behavior when attaching constraints at the hub account.  You must remove the constraints from the hub portfolio in order to share and add constraints at the spoke level.
This is not related to the reference architecture, please see the forum for general question about service catalog.
https://forums.aws.amazon.com/forum.jspa?forumID=198

see also:
https://docs.aws.amazon.com/servicecatalog/latest/adminguide/catalogs_portfolios_sharing.html
https://aws.amazon.com/blogs/mt/how-to-set-up-a-multi-region-multi-account-catalog-of-company-standard-aws-service-catalog-products/
https://aws.amazon.com/blogs/mt/aws-service-catalog-hub-and-spoke-model-how-to-automate-the-deployment-and-management-of-service-catalog-to-many-accounts/
